### ISSUE TITLE
Persistence Provider

### ISSUE THREAD

**Issue by rebeccavl1** [remarema/remarema-domain#1]
Hab ein Entity angelegt für die Klasse "Node" mit getter- und setter-Methoden. Weiters hab ich ein Session-Bean angelegt, wo ich Methoden, wie z.B.: createNode oder removeNode, erstellt habe. Habe noch eine Klasse NodeTest.java angelegt, in der ich Testdaten angelegt habe. 
Des weiteren habe ich die persistence.xml erzeugt und dort die Datenbankverbindung angegeben.

Beim Ausführen der NodeTest.java, bekomme ich aber immer eine Fehlermeldung:
       "No persistence providers available for "NodeServiceBean" after trying the following discovered      implementations: org.apache.openjpa.persistence.PersistenceProviderImpl"

Ich weiß leider nicht, wo mein Fehler ist und komme daher auch nicht mehr weiter.

![image](https://cloud.githubusercontent.com/assets/8970284/6225463/dc82a204-b68a-11e4-8f82-aa7604f97d7a.png)

**Comment by mrodler** [comment]
Hallo Rebecca,

dein PersistenceContext heißt `TestOpenJPAPersistence´ und nicht `NodeServiceBean`. Die Konfiguration befindet sich  in der Datei META-INF/persistence.xml 
```XML
  <persistence-unit name="TestOpenJPAPersistence" transaction-type="RESOURCE_LOCAL"> 
    <provider>org.apache.openjpa.persistence.PersistenceProviderImpl</provider> 
```
Die zweite Zeile `<provider...` ist normalerweise nicht notwendig.
